### PR TITLE
Json format for get-subnets

### PR DESCRIPTION
**Pull request by godlikeachilles**

### CODE REVIEW

**Comment by gobins** [comment]
Cannot compile. 
go build
_/Users/Gobin/go/src/github.com/godlikeachilles/goaws
./main.go:35: too many arguments in call to apihandlers.GetSubnetsFormatted

**Comment by godlikeachilles** [comment]
Because I changed the import back to gobins for merging
it will compile after merge.
or you can change it to godlikeachilles for testing
https://github.com/godlikeachilles/goaws/commit/6a1bafc5f2184bd1c055972518302d6127074b60

**Comment by gobins** [comment]
Can you send it to the integration branch?

**Comment by gobins** [comment]
Never mind, I will do it locally.

**Pull request merged**
